# Generated by Django 4.0.4 on 2022-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalseller',
            name='m_pesa_phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
