# Generated by Django 4.0.4 on 2022-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signalseller_m_pesa_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalseller',
            name='m_pesa_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
