# Generated by Django 4.0.4 on 2022-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodity', models.CharField(max_length=10)),
                ('mkt_range', models.CharField(max_length=20)),
                ('stop_loss', models.IntegerField()),
                ('take_profit1', models.IntegerField()),
                ('take_profit2', models.IntegerField()),
                ('take_profit3', models.IntegerField()),
            ],
        ),
    ]
