# Generated by Django 4.0.4 on 2022-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='action',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
