# Generated by Django 4.0.4 on 2022-06-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signalseller_m_pesa_phone_number'),
        ('signals', '0002_signal_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.signalseller'),
        ),
    ]
