# Generated by Django 4.0.4 on 2022-06-18 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
